controller_list:
  - name: fake_arm_controller
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
  - name: fake_hand_controller
    joints:
      []
  - name: fake_neo_mp_500_controller
    joints:
      - wheel_left_joint
      - wheel_right_joint
